// ─── Dummy static data for the food marketplace ───────────────────────────────

export const categories = [
  { id: 1, name: 'Pizza',       emoji: '🍕', color: 'bg-orange-100 dark:bg-orange-900/30',  count: 42 },
  { id: 2, name: 'Burgers',     emoji: '🍔', color: 'bg-yellow-100 dark:bg-yellow-900/30', count: 38 },
  { id: 3, name: 'Sushi',       emoji: '🍣', color: 'bg-pink-100 dark:bg-pink-900/30',     count: 25 },
  { id: 4, name: 'Desserts',    emoji: '🍰', color: 'bg-purple-100 dark:bg-purple-900/30', count: 56 },
  { id: 5, name: 'Biryani',     emoji: '🍛', color: 'bg-amber-100 dark:bg-amber-900/30',   count: 31 },
  { id: 6, name: 'Salads',      emoji: '🥗', color: 'bg-green-100 dark:bg-green-900/30',   count: 19 },
  { id: 7, name: 'Noodles',     emoji: '🍜', color: 'bg-red-100 dark:bg-red-900/30',       count: 27 },
  { id: 8, name: 'Ice Cream',   emoji: '🍦', color: 'bg-blue-100 dark:bg-blue-900/30',     count: 22 },
]

export const featuredShops = [
  {
    id: 1,
    name: "Burger Palace",
    type: "restaurant",
    cuisine: "American • Burgers",
    rating: 4.8,
    reviews: 2341,
    deliveryTime: "20-30 min",
    deliveryFee: "Free",
    minOrder: 149,
    discount: "20% OFF",
    tags: ["Bestseller", "Fast Delivery"],
    emoji: "🍔",
    bgColor: "from-orange-400 to-red-500",
    isOpen: true,
  },
  {
    id: 2,
    name: "Sushi World",
    type: "restaurant",
    cuisine: "Japanese • Sushi",
    rating: 4.6,
    reviews: 1892,
    deliveryTime: "30-45 min",
    deliveryFee: "₹29",
    minOrder: 299,
    discount: "15% OFF",
    tags: ["Premium", "Healthy"],
    emoji: "🍣",
    bgColor: "from-pink-400 to-rose-500",
    isOpen: true,
  },
  {
    id: 3,
    name: "Brew & Bites Café",
    type: "cafe",
    cuisine: "Café • Beverages",
    rating: 4.7,
    reviews: 3102,
    deliveryTime: "15-25 min",
    deliveryFee: "Free",
    minOrder: 99,
    discount: "Buy 1 Get 1",
    tags: ["Trending", "Coffee"],
    emoji: "☕",
    bgColor: "from-amber-400 to-orange-500",
    isOpen: true,
  },
  {
    id: 4,
    name: "Sweet Dreams",
    type: "sweet_shop",
    cuisine: "Desserts • Sweets",
    rating: 4.9,
    reviews: 987,
    deliveryTime: "25-35 min",
    deliveryFee: "₹19",
    minOrder: 199,
    discount: "10% OFF",
    tags: ["Top Rated", "Sweets"],
    emoji: "🍰",
    bgColor: "from-purple-400 to-pink-500",
    isOpen: true,
  },
  {
    id: 5,
    name: "Spice Garden",
    type: "restaurant",
    cuisine: "Indian • Biryani",
    rating: 4.5,
    reviews: 4210,
    deliveryTime: "35-50 min",
    deliveryFee: "Free",
    minOrder: 249,
    discount: "₹50 OFF",
    tags: ["Popular", "Spicy"],
    emoji: "🍛",
    bgColor: "from-green-400 to-emerald-500",
    isOpen: false,
  },
  {
    id: 6,
    name: "Pizza Hub",
    type: "restaurant",
    cuisine: "Italian • Pizza",
    rating: 4.4,
    reviews: 5678,
    deliveryTime: "25-40 min",
    deliveryFee: "₹39",
    minOrder: 199,
    discount: "30% OFF",
    tags: ["Bestseller"],
    emoji: "🍕",
    bgColor: "from-red-400 to-orange-500",
    isOpen: true,
  },
]

export const trendingProducts = [
  { id: 1, name: "Classic Smash Burger",    shop: "Burger Palace",    price: 249, originalPrice: 299, rating: 4.8, emoji: "🍔", tag: "Bestseller",  isVeg: false },
  { id: 2, name: "Spicy Tuna Roll",         shop: "Sushi World",      price: 349, originalPrice: 399, rating: 4.7, emoji: "🍣", tag: "Chef's Pick",  isVeg: false },
  { id: 3, name: "Cold Brew Coffee",        shop: "Brew & Bites",     price: 149, originalPrice: 179, rating: 4.9, emoji: "☕", tag: "Trending",     isVeg: true  },
  { id: 4, name: "Gulab Jamun Box",         shop: "Sweet Dreams",     price: 199, originalPrice: 249, rating: 4.9, emoji: "🍮", tag: "Top Rated",    isVeg: true  },
  { id: 5, name: "Chicken Biryani",         shop: "Spice Garden",     price: 299, originalPrice: 349, rating: 4.6, emoji: "🍛", tag: "Popular",      isVeg: false },
  { id: 6, name: "Margherita Pizza",        shop: "Pizza Hub",        price: 279, originalPrice: 329, rating: 4.5, emoji: "🍕", tag: "Classic",      isVeg: true  },
  { id: 7, name: "Mango Cheesecake",        shop: "Sweet Dreams",     price: 229, originalPrice: 269, rating: 4.8, emoji: "🍰", tag: "New",          isVeg: true  },
  { id: 8, name: "Pad Thai Noodles",        shop: "Noodle House",     price: 219, originalPrice: 259, rating: 4.4, emoji: "🍜", tag: "Spicy",        isVeg: false },
]

export const offerBanners = [
  {
    id: 1,
    title: "50% OFF",
    subtitle: "On your first order",
    description: "Use code FIRST50",
    emoji: "🎉",
    gradient: "from-orange-500 to-red-600",
    cta: "Order Now",
  },
  {
    id: 2,
    title: "Free Delivery",
    subtitle: "On orders above ₹299",
    description: "Valid all day today",
    emoji: "🚀",
    gradient: "from-purple-500 to-pink-600",
    cta: "Explore",
  },
  {
    id: 3,
    title: "Buy 1 Get 1",
    subtitle: "On selected cafés",
    description: "Weekend special offer",
    emoji: "☕",
    gradient: "from-amber-500 to-orange-600",
    cta: "Grab Deal",
  },
]

export const heroSlides = [
  {
    id: 1,
    headline: "Hungry? We've Got You",
    subtext: "Order from 500+ restaurants, cafés & sweet shops near you",
    emoji: "🍔",
    gradient: "from-orange-500 via-red-500 to-pink-600",
    cta: "Order Now",
  },
  {
    id: 2,
    headline: "Fresh Brews, Fast Delivery",
    subtext: "Your favourite café drinks delivered in under 30 minutes",
    emoji: "☕",
    gradient: "from-amber-500 via-orange-500 to-red-500",
    cta: "Explore Cafés",
  },
  {
    id: 3,
    headline: "Sweet Cravings? Sorted.",
    subtext: "Mithai, cakes, desserts — delivered fresh to your door",
    emoji: "🍰",
    gradient: "from-purple-500 via-pink-500 to-rose-500",
    cta: "Shop Sweets",
  },
]

export const navLinks = [
  { label: 'Home',        path: '/' },
  { label: 'Restaurants', path: '/restaurants' },
  { label: 'Cafes',       path: '/cafes' },
  { label: 'Sweet Shops', path: '/sweet-shops' },
]
