// ─── Seed Data ────────────────────────────────────────────────────────────────
// All dummy JSON data for the FoodieHub marketplace.
// This file is the single source of truth for seeding localStorage on first load.

// ─── Storage Keys ─────────────────────────────────────────────────────────────
export const STORAGE_KEYS = {
  SEEDED:     'fh_seeded',
  CATEGORIES: 'fh_categories',
  SHOPS:      'fh_shops',
  PRODUCTS:   'fh_products',
  USERS:      'fh_users',
  ORDERS:     'fh_orders',
  OFFERS:     'fh_offers',
}

// ─── Categories ───────────────────────────────────────────────────────────────
export const SEED_CATEGORIES = [
  { id: 'cat-1',  name: 'Pizza',       emoji: '🍕', shopType: 'restaurant',  color: 'bg-orange-100 dark:bg-orange-900/30',  count: 42 },
  { id: 'cat-2',  name: 'Burgers',     emoji: '🍔', shopType: 'restaurant',  color: 'bg-yellow-100 dark:bg-yellow-900/30', count: 38 },
  { id: 'cat-3',  name: 'Sushi',       emoji: '🍣', shopType: 'restaurant',  color: 'bg-pink-100 dark:bg-pink-900/30',     count: 25 },
  { id: 'cat-4',  name: 'Desserts',    emoji: '🍰', shopType: 'sweet_shop',  color: 'bg-purple-100 dark:bg-purple-900/30', count: 56 },
  { id: 'cat-5',  name: 'Biryani',     emoji: '🍛', shopType: 'restaurant',  color: 'bg-amber-100 dark:bg-amber-900/30',   count: 31 },
  { id: 'cat-6',  name: 'Salads',      emoji: '🥗', shopType: 'restaurant',  color: 'bg-green-100 dark:bg-green-900/30',   count: 19 },
  { id: 'cat-7',  name: 'Noodles',     emoji: '🍜', shopType: 'restaurant',  color: 'bg-red-100 dark:bg-red-900/30',       count: 27 },
  { id: 'cat-8',  name: 'Ice Cream',   emoji: '🍦', shopType: 'sweet_shop',  color: 'bg-blue-100 dark:bg-blue-900/30',     count: 22 },
  { id: 'cat-9',  name: 'Coffee',      emoji: '☕', shopType: 'cafe',        color: 'bg-amber-100 dark:bg-amber-900/30',   count: 34 },
  { id: 'cat-10', name: 'Sandwiches',  emoji: '🥪', shopType: 'cafe',        color: 'bg-lime-100 dark:bg-lime-900/30',     count: 18 },
  { id: 'cat-11', name: 'Mithai',      emoji: '🍮', shopType: 'sweet_shop',  color: 'bg-rose-100 dark:bg-rose-900/30',     count: 45 },
  { id: 'cat-12', name: 'Wraps',       emoji: '🌯', shopType: 'restaurant',  color: 'bg-teal-100 dark:bg-teal-900/30',     count: 21 },
]

// ─── Shops ────────────────────────────────────────────────────────────────────
// category: 'restaurant' | 'cafe' | 'sweet_shop'
export const SEED_SHOPS = [
  // ── Restaurants ──────────────────────────────────────────────────────────
  {
    id: 'shop-1',
    name: 'Burger Palace',
    category: 'restaurant',
    logo: '🍔',
    banner: 'from-orange-400 to-red-500',
    address: '12, Connaught Place, New Delhi',
    rating: 4.8,
    reviewCount: 2341,
    deliveryTime: '20-30 min',
    deliveryFee: 0,
    minOrder: 149,
    whatsappNumber: '919876543210',
    openStatus: true,
    cuisine: 'American • Burgers',
    tags: ['Bestseller', 'Fast Delivery'],
    discount: '20% OFF',
  },
  {
    id: 'shop-2',
    name: 'Sushi World',
    category: 'restaurant',
    logo: '🍣',
    banner: 'from-pink-400 to-rose-500',
    address: '5, Hauz Khas Village, New Delhi',
    rating: 4.6,
    reviewCount: 1892,
    deliveryTime: '30-45 min',
    deliveryFee: 29,
    minOrder: 299,
    whatsappNumber: '919876543211',
    openStatus: true,
    cuisine: 'Japanese • Sushi',
    tags: ['Premium', 'Healthy'],
    discount: '15% OFF',
  },
  {
    id: 'shop-3',
    name: 'Spice Garden',
    category: 'restaurant',
    logo: '🍛',
    banner: 'from-green-400 to-emerald-500',
    address: '88, Lajpat Nagar, New Delhi',
    rating: 4.5,
    reviewCount: 4210,
    deliveryTime: '35-50 min',
    deliveryFee: 0,
    minOrder: 249,
    whatsappNumber: '919876543212',
    openStatus: false,
    cuisine: 'Indian • Biryani',
    tags: ['Popular', 'Spicy'],
    discount: '₹50 OFF',
  },
  {
    id: 'shop-4',
    name: 'Pizza Hub',
    category: 'restaurant',
    logo: '🍕',
    banner: 'from-red-400 to-orange-500',
    address: '3, Rajouri Garden, New Delhi',
    rating: 4.4,
    reviewCount: 5678,
    deliveryTime: '25-40 min',
    deliveryFee: 39,
    minOrder: 199,
    whatsappNumber: '919876543213',
    openStatus: true,
    cuisine: 'Italian • Pizza',
    tags: ['Bestseller'],
    discount: '30% OFF',
  },
  {
    id: 'shop-5',
    name: 'Noodle House',
    category: 'restaurant',
    logo: '🍜',
    banner: 'from-yellow-400 to-amber-500',
    address: '21, Saket, New Delhi',
    rating: 4.3,
    reviewCount: 1120,
    deliveryTime: '25-35 min',
    deliveryFee: 19,
    minOrder: 179,
    whatsappNumber: '919876543214',
    openStatus: true,
    cuisine: 'Pan-Asian • Noodles',
    tags: ['Trending'],
    discount: null,
  },
  {
    id: 'shop-6',
    name: 'The Wrap Co.',
    category: 'restaurant',
    logo: '🌯',
    banner: 'from-teal-400 to-cyan-500',
    address: '7, Vasant Kunj, New Delhi',
    rating: 4.2,
    reviewCount: 876,
    deliveryTime: '15-25 min',
    deliveryFee: 0,
    minOrder: 129,
    whatsappNumber: '919876543215',
    openStatus: true,
    cuisine: 'Fusion • Wraps',
    tags: ['Fast Delivery', 'Healthy'],
    discount: '10% OFF',
  },

  // ── Cafes ─────────────────────────────────────────────────────────────────
  {
    id: 'shop-7',
    name: 'Brew & Bites Café',
    category: 'cafe',
    logo: '☕',
    banner: 'from-amber-400 to-orange-500',
    address: '14, Khan Market, New Delhi',
    rating: 4.7,
    reviewCount: 3102,
    deliveryTime: '15-25 min',
    deliveryFee: 0,
    minOrder: 99,
    whatsappNumber: '919876543216',
    openStatus: true,
    cuisine: 'Café • Beverages',
    tags: ['Trending', 'Coffee'],
    discount: 'Buy 1 Get 1',
  },
  {
    id: 'shop-8',
    name: 'The Cozy Corner',
    category: 'cafe',
    logo: '🫖',
    banner: 'from-rose-400 to-pink-500',
    address: '9, Mehrauli, New Delhi',
    rating: 4.5,
    reviewCount: 1450,
    deliveryTime: '20-30 min',
    deliveryFee: 29,
    minOrder: 149,
    whatsappNumber: '919876543217',
    openStatus: true,
    cuisine: 'Café • Snacks',
    tags: ['Cozy', 'Instagrammable'],
    discount: '15% OFF',
  },
  {
    id: 'shop-9',
    name: 'Grind & Sip',
    category: 'cafe',
    logo: '🧋',
    banner: 'from-violet-400 to-purple-500',
    address: '33, Nehru Place, New Delhi',
    rating: 4.6,
    reviewCount: 2200,
    deliveryTime: '20-35 min',
    deliveryFee: 0,
    minOrder: 119,
    whatsappNumber: '919876543218',
    openStatus: true,
    cuisine: 'Café • Boba • Coffee',
    tags: ['Boba', 'Specialty Coffee'],
    discount: null,
  },

  // ── Sweet Shops ───────────────────────────────────────────────────────────
  {
    id: 'shop-10',
    name: 'Sweet Dreams',
    category: 'sweet_shop',
    logo: '🍰',
    banner: 'from-purple-400 to-pink-500',
    address: '2, Chandni Chowk, New Delhi',
    rating: 4.9,
    reviewCount: 987,
    deliveryTime: '25-35 min',
    deliveryFee: 19,
    minOrder: 199,
    whatsappNumber: '919876543219',
    openStatus: true,
    cuisine: 'Desserts • Cakes',
    tags: ['Top Rated', 'Sweets'],
    discount: '10% OFF',
  },
  {
    id: 'shop-11',
    name: 'Mithai Mandir',
    category: 'sweet_shop',
    logo: '🍮',
    banner: 'from-yellow-400 to-orange-400',
    address: '45, Karol Bagh, New Delhi',
    rating: 4.8,
    reviewCount: 3400,
    deliveryTime: '30-45 min',
    deliveryFee: 0,
    minOrder: 249,
    whatsappNumber: '919876543220',
    openStatus: true,
    cuisine: 'Indian Sweets • Mithai',
    tags: ['Traditional', 'Bestseller'],
    discount: '₹30 OFF',
  },
  {
    id: 'shop-12',
    name: 'Chill & Scoop',
    category: 'sweet_shop',
    logo: '🍦',
    banner: 'from-sky-400 to-blue-500',
    address: '18, Dwarka, New Delhi',
    rating: 4.4,
    reviewCount: 760,
    deliveryTime: '20-30 min',
    deliveryFee: 29,
    minOrder: 149,
    whatsappNumber: '919876543221',
    openStatus: false,
    cuisine: 'Ice Cream • Gelato',
    tags: ['Seasonal', 'Kids Favourite'],
    discount: null,
  },
]

// ─── Products ─────────────────────────────────────────────────────────────────
// image: emoji string used as placeholder (swap for real URLs later)
export const SEED_PRODUCTS = [
  // ── Burger Palace (shop-1) ────────────────────────────────────────────────
  {
    id: 'prod-1',
    shopId: 'shop-1',
    image: '🍔',
    name: 'Classic Smash Burger',
    description: 'Double smash patty, American cheese, pickles, special sauce on a brioche bun.',
    price: 249,
    originalPrice: 299,
    isVeg: false,
    category: 'Burgers',
    rating: 4.8,
    tag: 'Bestseller',
    inStock: true,
  },
  {
    id: 'prod-2',
    shopId: 'shop-1',
    image: '🍟',
    name: 'Loaded Cheese Fries',
    description: 'Crispy fries smothered in cheddar sauce, jalapeños and crispy onions.',
    price: 149,
    originalPrice: 179,
    isVeg: true,
    category: 'Sides',
    rating: 4.6,
    tag: 'Popular',
    inStock: true,
  },
  {
    id: 'prod-3',
    shopId: 'shop-1',
    image: '🥤',
    name: 'Thick Oreo Shake',
    description: 'Creamy vanilla shake blended with Oreo cookies and topped with whipped cream.',
    price: 179,
    originalPrice: 199,
    isVeg: true,
    category: 'Beverages',
    rating: 4.7,
    tag: 'Trending',
    inStock: true,
  },
  {
    id: 'prod-4',
    shopId: 'shop-1',
    image: '🌶️',
    name: 'Spicy Chicken Burger',
    description: 'Crispy fried chicken thigh, sriracha mayo, coleslaw, pickled cucumber.',
    price: 279,
    originalPrice: 319,
    isVeg: false,
    category: 'Burgers',
    rating: 4.7,
    tag: 'Spicy',
    inStock: true,
  },

  // ── Sushi World (shop-2) ──────────────────────────────────────────────────
  {
    id: 'prod-5',
    shopId: 'shop-2',
    image: '🍣',
    name: 'Spicy Tuna Roll (8 pcs)',
    description: 'Fresh tuna, cucumber, avocado, spicy mayo, sesame seeds.',
    price: 349,
    originalPrice: 399,
    isVeg: false,
    category: 'Sushi',
    rating: 4.7,
    tag: "Chef's Pick",
    inStock: true,
  },
  {
    id: 'prod-6',
    shopId: 'shop-2',
    image: '🥢',
    name: 'Veggie Dragon Roll',
    description: 'Avocado, cucumber, cream cheese, topped with mango slices.',
    price: 299,
    originalPrice: 349,
    isVeg: true,
    category: 'Sushi',
    rating: 4.5,
    tag: 'Healthy',
    inStock: true,
  },
  {
    id: 'prod-7',
    shopId: 'shop-2',
    image: '🍱',
    name: 'Bento Box — Chicken Teriyaki',
    description: 'Grilled chicken teriyaki, steamed rice, miso soup, edamame, pickled ginger.',
    price: 449,
    originalPrice: 499,
    isVeg: false,
    category: 'Bento',
    rating: 4.8,
    tag: 'Premium',
    inStock: true,
  },

  // ── Spice Garden (shop-3) ─────────────────────────────────────────────────
  {
    id: 'prod-8',
    shopId: 'shop-3',
    image: '🍛',
    name: 'Chicken Biryani',
    description: 'Slow-cooked basmati rice with tender chicken, saffron, fried onions & raita.',
    price: 299,
    originalPrice: 349,
    isVeg: false,
    category: 'Biryani',
    rating: 4.6,
    tag: 'Popular',
    inStock: true,
  },
  {
    id: 'prod-9',
    shopId: 'shop-3',
    image: '🥘',
    name: 'Paneer Butter Masala',
    description: 'Cottage cheese cubes in a rich, creamy tomato-cashew gravy. Served with naan.',
    price: 249,
    originalPrice: 289,
    isVeg: true,
    category: 'Curries',
    rating: 4.5,
    tag: 'Classic',
    inStock: true,
  },
  {
    id: 'prod-10',
    shopId: 'shop-3',
    image: '🫓',
    name: 'Garlic Naan (2 pcs)',
    description: 'Soft tandoor-baked naan brushed with garlic butter and fresh coriander.',
    price: 79,
    originalPrice: 99,
    isVeg: true,
    category: 'Breads',
    rating: 4.4,
    tag: 'Must Try',
    inStock: true,
  },

  // ── Pizza Hub (shop-4) ────────────────────────────────────────────────────
  {
    id: 'prod-11',
    shopId: 'shop-4',
    image: '🍕',
    name: 'Margherita Pizza',
    description: 'San Marzano tomato sauce, fresh mozzarella, basil on a thin crispy crust.',
    price: 279,
    originalPrice: 329,
    isVeg: true,
    category: 'Pizza',
    rating: 4.5,
    tag: 'Classic',
    inStock: true,
  },
  {
    id: 'prod-12',
    shopId: 'shop-4',
    image: '🧀',
    name: 'BBQ Chicken Pizza',
    description: 'Smoky BBQ sauce, grilled chicken, red onion, mozzarella, coriander.',
    price: 349,
    originalPrice: 399,
    isVeg: false,
    category: 'Pizza',
    rating: 4.6,
    tag: 'Bestseller',
    inStock: true,
  },
  {
    id: 'prod-13',
    shopId: 'shop-4',
    image: '🫙',
    name: 'Pasta Arrabbiata',
    description: 'Penne in a fiery tomato-garlic sauce with fresh basil and parmesan.',
    price: 219,
    originalPrice: 259,
    isVeg: true,
    category: 'Pasta',
    rating: 4.3,
    tag: 'Spicy',
    inStock: true,
  },

  // ── Noodle House (shop-5) ─────────────────────────────────────────────────
  {
    id: 'prod-14',
    shopId: 'shop-5',
    image: '🍜',
    name: 'Pad Thai Noodles',
    description: 'Stir-fried rice noodles, egg, bean sprouts, peanuts, tamarind sauce.',
    price: 219,
    originalPrice: 259,
    isVeg: false,
    category: 'Noodles',
    rating: 4.4,
    tag: 'Spicy',
    inStock: true,
  },
  {
    id: 'prod-15',
    shopId: 'shop-5',
    image: '🍲',
    name: 'Veg Ramen Bowl',
    description: 'Rich miso broth, ramen noodles, tofu, corn, nori, soft-boiled egg.',
    price: 249,
    originalPrice: 289,
    isVeg: true,
    category: 'Noodles',
    rating: 4.5,
    tag: 'Healthy',
    inStock: true,
  },

  // ── Brew & Bites Café (shop-7) ────────────────────────────────────────────
  {
    id: 'prod-16',
    shopId: 'shop-7',
    image: '☕',
    name: 'Cold Brew Coffee',
    description: '18-hour cold-steeped single-origin coffee served over ice. Smooth & bold.',
    price: 149,
    originalPrice: 179,
    isVeg: true,
    category: 'Coffee',
    rating: 4.9,
    tag: 'Trending',
    inStock: true,
  },
  {
    id: 'prod-17',
    shopId: 'shop-7',
    image: '🥐',
    name: 'Butter Croissant',
    description: 'Flaky, buttery French croissant baked fresh every morning.',
    price: 89,
    originalPrice: 109,
    isVeg: true,
    category: 'Bakery',
    rating: 4.7,
    tag: 'Fresh',
    inStock: true,
  },
  {
    id: 'prod-18',
    shopId: 'shop-7',
    image: '🧇',
    name: 'Avocado Toast',
    description: 'Sourdough toast, smashed avocado, cherry tomatoes, feta, chilli flakes.',
    price: 199,
    originalPrice: 229,
    isVeg: true,
    category: 'Sandwiches',
    rating: 4.6,
    tag: 'Healthy',
    inStock: true,
  },

  // ── Grind & Sip (shop-9) ──────────────────────────────────────────────────
  {
    id: 'prod-19',
    shopId: 'shop-9',
    image: '🧋',
    name: 'Brown Sugar Boba',
    description: 'Creamy milk tea with chewy tapioca pearls and caramelised brown sugar.',
    price: 179,
    originalPrice: 209,
    isVeg: true,
    category: 'Boba',
    rating: 4.8,
    tag: 'New',
    inStock: true,
  },
  {
    id: 'prod-20',
    shopId: 'shop-9',
    image: '🍵',
    name: 'Matcha Latte',
    description: 'Ceremonial-grade matcha whisked with oat milk. Hot or iced.',
    price: 159,
    originalPrice: 189,
    isVeg: true,
    category: 'Coffee',
    rating: 4.7,
    tag: 'Healthy',
    inStock: true,
  },

  // ── Sweet Dreams (shop-10) ────────────────────────────────────────────────
  {
    id: 'prod-21',
    shopId: 'shop-10',
    image: '🍰',
    name: 'Mango Cheesecake',
    description: 'Creamy New York-style cheesecake with a fresh Alphonso mango glaze.',
    price: 229,
    originalPrice: 269,
    isVeg: true,
    category: 'Desserts',
    rating: 4.8,
    tag: 'New',
    inStock: true,
  },
  {
    id: 'prod-22',
    shopId: 'shop-10',
    image: '🍫',
    name: 'Dark Chocolate Truffle Cake',
    description: 'Dense, fudgy chocolate cake with ganache frosting and cocoa dusting.',
    price: 249,
    originalPrice: 299,
    isVeg: true,
    category: 'Desserts',
    rating: 4.9,
    tag: 'Top Rated',
    inStock: true,
  },

  // ── Mithai Mandir (shop-11) ───────────────────────────────────────────────
  {
    id: 'prod-23',
    shopId: 'shop-11',
    image: '🍮',
    name: 'Gulab Jamun Box (12 pcs)',
    description: 'Soft khoya dumplings soaked in rose-cardamom sugar syrup.',
    price: 199,
    originalPrice: 249,
    isVeg: true,
    category: 'Mithai',
    rating: 4.9,
    tag: 'Top Rated',
    inStock: true,
  },
  {
    id: 'prod-24',
    shopId: 'shop-11',
    image: '🟡',
    name: 'Kaju Katli (250g)',
    description: 'Premium cashew fudge with silver vark. A festive classic.',
    price: 349,
    originalPrice: 399,
    isVeg: true,
    category: 'Mithai',
    rating: 4.8,
    tag: 'Premium',
    inStock: true,
  },

  // ── Chill & Scoop (shop-12) ───────────────────────────────────────────────
  {
    id: 'prod-25',
    shopId: 'shop-12',
    image: '🍦',
    name: 'Belgian Chocolate Gelato',
    description: 'Rich, creamy gelato made with 70% Belgian dark chocolate.',
    price: 129,
    originalPrice: 149,
    isVeg: true,
    category: 'Ice Cream',
    rating: 4.6,
    tag: 'Classic',
    inStock: false,
  },
  {
    id: 'prod-26',
    shopId: 'shop-12',
    image: '🍧',
    name: 'Mango Sorbet',
    description: 'Dairy-free Alphonso mango sorbet. Refreshing and light.',
    price: 109,
    originalPrice: 129,
    isVeg: true,
    category: 'Ice Cream',
    rating: 4.5,
    tag: 'Vegan',
    inStock: false,
  },
]

// ─── Users ────────────────────────────────────────────────────────────────────
export const SEED_USERS = [
  {
    id: 'user-1',
    name: 'Rahul Sharma',
    email: 'rahul@example.com',
    phone: '9876543210',
    avatar: '👨',
    addresses: [
      { id: 'addr-1', label: 'Home',   line: '42, Sector 15, Dwarka, New Delhi', pincode: '110078', isDefault: true  },
      { id: 'addr-2', label: 'Office', line: '7th Floor, Cyber Hub, Gurugram',   pincode: '122002', isDefault: false },
    ],
    createdAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Priya Mehta',
    email: 'priya@example.com',
    phone: '9876543211',
    avatar: '👩',
    addresses: [
      { id: 'addr-3', label: 'Home', line: '12, Green Park Extension, New Delhi', pincode: '110016', isDefault: true },
    ],
    createdAt: '2024-02-20T09:30:00Z',
  },
  {
    id: 'user-3',
    name: 'Amit Kumar',
    email: 'amit@example.com',
    phone: '9876543212',
    avatar: '🧑',
    addresses: [
      { id: 'addr-4', label: 'Home', line: '88, Rohini Sector 3, New Delhi', pincode: '110085', isDefault: true },
    ],
    createdAt: '2024-03-05T14:00:00Z',
  },
]

// ─── Orders ───────────────────────────────────────────────────────────────────
// status: 'pending' | 'confirmed' | 'preparing' | 'on_the_way' | 'delivered' | 'cancelled'
export const SEED_ORDERS = [
  {
    id: 'ord-1001',
    userId: 'user-1',
    shopId: 'shop-1',
    shopName: 'Burger Palace',
    shopLogo: '🍔',
    items: [
      { productId: 'prod-1', name: 'Classic Smash Burger', price: 249, qty: 2, image: '🍔' },
      { productId: 'prod-2', name: 'Loaded Cheese Fries',  price: 149, qty: 1, image: '🍟' },
    ],
    subtotal: 647,
    deliveryFee: 0,
    discount: 0,
    total: 647,
    status: 'delivered',
    paymentMethod: 'UPI',
    address: '42, Sector 15, Dwarka, New Delhi',
    placedAt: '2025-05-08T14:30:00Z',
    deliveredAt: '2025-05-08T15:05:00Z',
  },
  {
    id: 'ord-1002',
    userId: 'user-1',
    shopId: 'shop-7',
    shopName: 'Brew & Bites Café',
    shopLogo: '☕',
    items: [
      { productId: 'prod-16', name: 'Cold Brew Coffee', price: 149, qty: 1, image: '☕' },
      { productId: 'prod-17', name: 'Butter Croissant', price: 89,  qty: 2, image: '🥐' },
    ],
    subtotal: 327,
    deliveryFee: 0,
    discount: 0,
    total: 327,
    status: 'on_the_way',
    paymentMethod: 'Card',
    address: '42, Sector 15, Dwarka, New Delhi',
    placedAt: '2025-05-09T11:15:00Z',
    deliveredAt: null,
  },
  {
    id: 'ord-1003',
    userId: 'user-1',
    shopId: 'shop-10',
    shopName: 'Sweet Dreams',
    shopLogo: '🍰',
    items: [
      { productId: 'prod-21', name: 'Mango Cheesecake',           price: 229, qty: 1, image: '🍰' },
      { productId: 'prod-22', name: 'Dark Chocolate Truffle Cake', price: 249, qty: 1, image: '🍫' },
    ],
    subtotal: 478,
    deliveryFee: 19,
    discount: 48,
    total: 449,
    status: 'preparing',
    paymentMethod: 'COD',
    address: '42, Sector 15, Dwarka, New Delhi',
    placedAt: '2025-05-09T12:00:00Z',
    deliveredAt: null,
  },
  {
    id: 'ord-1004',
    userId: 'user-2',
    shopId: 'shop-4',
    shopName: 'Pizza Hub',
    shopLogo: '🍕',
    items: [
      { productId: 'prod-11', name: 'Margherita Pizza', price: 279, qty: 1, image: '🍕' },
    ],
    subtotal: 279,
    deliveryFee: 39,
    discount: 0,
    total: 318,
    status: 'cancelled',
    paymentMethod: 'UPI',
    address: '12, Green Park Extension, New Delhi',
    placedAt: '2025-05-07T20:00:00Z',
    deliveredAt: null,
  },
  {
    id: 'ord-1005',
    userId: 'user-2',
    shopId: 'shop-11',
    shopName: 'Mithai Mandir',
    shopLogo: '🍮',
    items: [
      { productId: 'prod-23', name: 'Gulab Jamun Box (12 pcs)', price: 199, qty: 2, image: '🍮' },
      { productId: 'prod-24', name: 'Kaju Katli (250g)',         price: 349, qty: 1, image: '🟡' },
    ],
    subtotal: 747,
    deliveryFee: 0,
    discount: 30,
    total: 717,
    status: 'delivered',
    paymentMethod: 'Card',
    address: '12, Green Park Extension, New Delhi',
    placedAt: '2025-05-06T16:45:00Z',
    deliveredAt: '2025-05-06T17:30:00Z',
  },
]

// ─── Offers ───────────────────────────────────────────────────────────────────
// type: 'percentage' | 'flat' | 'bogo' | 'free_delivery'
export const SEED_OFFERS = [
  {
    id: 'offer-1',
    code: 'FIRST50',
    title: '50% OFF',
    subtitle: 'On your first order',
    description: 'Get 50% off up to ₹100 on your very first order.',
    emoji: '🎉',
    gradient: 'from-orange-500 to-red-600',
    type: 'percentage',
    value: 50,
    maxDiscount: 100,
    minOrder: 199,
    applicableOn: 'all',
    expiresAt: '2025-12-31T23:59:59Z',
    isActive: true,
  },
  {
    id: 'offer-2',
    code: 'FREEDEL',
    title: 'Free Delivery',
    subtitle: 'On orders above ₹299',
    description: 'No delivery charges on orders ₹299 and above. Valid all day.',
    emoji: '🚀',
    gradient: 'from-purple-500 to-pink-600',
    type: 'free_delivery',
    value: 0,
    maxDiscount: null,
    minOrder: 299,
    applicableOn: 'all',
    expiresAt: '2025-12-31T23:59:59Z',
    isActive: true,
  },
  {
    id: 'offer-3',
    code: 'CAFEBOGO',
    title: 'Buy 1 Get 1',
    subtitle: 'On selected cafés',
    description: 'Buy any beverage and get one free at participating cafés. Weekend only.',
    emoji: '☕',
    gradient: 'from-amber-500 to-orange-600',
    type: 'bogo',
    value: 100,
    maxDiscount: null,
    minOrder: 149,
    applicableOn: 'cafe',
    expiresAt: '2025-05-11T23:59:59Z',
    isActive: true,
  },
  {
    id: 'offer-4',
    code: 'SWEET10',
    title: '10% OFF',
    subtitle: 'On all sweet shops',
    description: '10% off on your order from any sweet shop. No minimum order.',
    emoji: '🍰',
    gradient: 'from-pink-500 to-rose-600',
    type: 'percentage',
    value: 10,
    maxDiscount: 50,
    minOrder: 0,
    applicableOn: 'sweet_shop',
    expiresAt: '2025-06-30T23:59:59Z',
    isActive: true,
  },
  {
    id: 'offer-5',
    code: 'FLAT50',
    title: '₹50 OFF',
    subtitle: 'On orders above ₹399',
    description: 'Flat ₹50 off on orders of ₹399 or more from any restaurant.',
    emoji: '🍽️',
    gradient: 'from-green-500 to-teal-600',
    type: 'flat',
    value: 50,
    maxDiscount: 50,
    minOrder: 399,
    applicableOn: 'restaurant',
    expiresAt: '2025-07-31T23:59:59Z',
    isActive: false,
  },
]
